package modelo.entidad;
// Generated Jul 22, 2020 12:32:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private int idAuditoria;
     private int idSolicitud;
     private Date fecha;
     private String estadoInicial;
     private String estadoSiguiente;

    public Auditoria() {
    }

    public Auditoria(int idAuditoria, int idSolicitud, Date fecha, String estadoInicial, String estadoSiguiente) {
       this.idAuditoria = idAuditoria;
       this.idSolicitud = idSolicitud;
       this.fecha = fecha;
       this.estadoInicial = estadoInicial;
       this.estadoSiguiente = estadoSiguiente;
    }
   
    public int getIdAuditoria() {
        return this.idAuditoria;
    }
    
    public void setIdAuditoria(int idAuditoria) {
        this.idAuditoria = idAuditoria;
    }
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstadoInicial() {
        return this.estadoInicial;
    }
    
    public void setEstadoInicial(String estadoInicial) {
        this.estadoInicial = estadoInicial;
    }
    public String getEstadoSiguiente() {
        return this.estadoSiguiente;
    }
    
    public void setEstadoSiguiente(String estadoSiguiente) {
        this.estadoSiguiente = estadoSiguiente;
    }




}


