package modelo.entidad;
// Generated Jul 22, 2020 12:32:52 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * Cliente generated by hbm2java
 */

@Entity
@Table(name="CLIENTE")
public class Cliente  implements java.io.Serializable {


    @Id
    @Column(name = "id_cliente", unique = true, nullable = false)
     private String idCliente;
    @Column(name = "primer_nombre", unique = false, nullable = false, length = 255)
     private String primerNombre;
    @Column(name = "segundo_nombre", unique = false, nullable = false, length = 255)
     private String segundoNombre;
    @Column(name = "primer_apellido", unique = false, nullable = false, length = 255)
     private String primerApellido;
    @Column(name = "segundo_apellido", unique = false, nullable = false, length = 255)
     private String segundoApellido;
    @Column(name = "telefono", unique = false, nullable = false, length = 255)
     private String telefono;
    @Column(name = "celular", unique = false, nullable = false, length = 255)
     private String celular;
    @Column(name = "correo", unique = false, nullable = false, length = 255)
     private String correo;
    @Column(name = "departamento", unique = false, nullable = false, length = 255)
     private String departamento;
    @Column(name = "ciudad", unique = false, nullable = false, length = 255)
     private String ciudad;
    @Column(name = "direccion", unique = false, nullable = false, length = 255)
     private String direccion;
    @Column(name = "estado", unique = false, nullable = false, length = 255)
     private String estado;
   @Column(name = "usuario", unique = false, nullable = false, length = 255)
     private String usuario;
   @Column(name = "contrasena", unique = false, nullable = false, length = 255)
     private String contrasena;
   
   
    public Cliente() {
    }

    public Cliente(String idCliente, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String telefono, String celular, String correo, String departamento, String ciudad, String direccion, String estado, String usuario, String contrasena) {
        this.idCliente = idCliente;
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.telefono = telefono;
        this.celular = celular;
        this.correo = correo;
        this.departamento = departamento;
        this.ciudad = ciudad;
        this.direccion = direccion;
        this.estado = estado;
        this.usuario = usuario;
        this.contrasena = contrasena;
    }
    
   
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasena() {
        return contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


