package modelo.entidad;
// Generated Jul 22, 2020 12:32:52 PM by Hibernate Tools 4.3.1



/**
 * Documentos generated by hbm2java
 */
public class Documentos  implements java.io.Serializable {


     private int idDocumento;
     private int idSolicitud;
     private String urlDocumento;

    public Documentos() {
    }

    public Documentos(int idDocumento, int idSolicitud, String urlDocumento) {
       this.idDocumento = idDocumento;
       this.idSolicitud = idSolicitud;
       this.urlDocumento = urlDocumento;
    }
   
    public int getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(int idDocumento) {
        this.idDocumento = idDocumento;
    }
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public String getUrlDocumento() {
        return this.urlDocumento;
    }
    
    public void setUrlDocumento(String urlDocumento) {
        this.urlDocumento = urlDocumento;
    }




}


