package modelo.entidad;
// Generated Jul 22, 2020 12:32:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EventosAprobaciones generated by hbm2java
 */
public class EventosAprobaciones  implements java.io.Serializable {


     private int idEvento;
     private int idSolicitud;
     private Date fecha;
     private String estadoAprobacion;

    public EventosAprobaciones() {
    }

    public EventosAprobaciones(int idEvento, int idSolicitud, Date fecha, String estadoAprobacion) {
       this.idEvento = idEvento;
       this.idSolicitud = idSolicitud;
       this.fecha = fecha;
       this.estadoAprobacion = estadoAprobacion;
    }
   
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstadoAprobacion() {
        return this.estadoAprobacion;
    }
    
    public void setEstadoAprobacion(String estadoAprobacion) {
        this.estadoAprobacion = estadoAprobacion;
    }




}


