package modelo.entidad;
// Generated Jul 22, 2020 12:32:52 PM by Hibernate Tools 4.3.1



/**
 * Peticiones generated by hbm2java
 */
public class Peticiones  implements java.io.Serializable {


     private int idPeticion;
     private int idProducto;
     private String tipoPeticion;
     private String descripcion;
     private String estado;

    public Peticiones() {
    }

    public Peticiones(int idPeticion, int idProducto, String tipoPeticion, String descripcion, String estado) {
       this.idPeticion = idPeticion;
       this.idProducto = idProducto;
       this.tipoPeticion = tipoPeticion;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdPeticion() {
        return this.idPeticion;
    }
    
    public void setIdPeticion(int idPeticion) {
        this.idPeticion = idPeticion;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getTipoPeticion() {
        return this.tipoPeticion;
    }
    
    public void setTipoPeticion(String tipoPeticion) {
        this.tipoPeticion = tipoPeticion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


