package modelo.entidad;
// Generated Jul 22, 2020 12:32:52 PM by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private int tipoProducto;
     private int montoProducto;
     private String estado;
     private int idSolicitud;
     private int idCliente;

    public Producto() {
    }

    public Producto(int idProducto, int tipoProducto, int montoProducto, String estado, int idSolicitud, int idCliente) {
       this.idProducto = idProducto;
       this.tipoProducto = tipoProducto;
       this.montoProducto = montoProducto;
       this.estado = estado;
       this.idSolicitud = idSolicitud;
       this.idCliente = idCliente;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public int getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(int tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public int getMontoProducto() {
        return this.montoProducto;
    }
    
    public void setMontoProducto(int montoProducto) {
        this.montoProducto = montoProducto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }




}


