package modelo.entidad;
// Generated Jul 22, 2020 12:32:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Solicitudes generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUDES")  
public class Solicitudes implements java.io.Serializable {

    @Id
    @Column(name = "id_solicitud", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int idSolicitud;
    @Column(name = "tipo_solicitud", unique = false, nullable = false, length = 255)
    private String tipoSolicitud;
    @Column(name = "id_cliente", unique = false, nullable = false, length = 255)
    private String idCliente;
    @Column(name = "id_referencia", unique = false, nullable = false, length = 255)
    private String idReferencia;
    @Column(name = "nombre_referencia", unique = false, nullable = false, length = 255)
    private String nombreReferencia;
    @Column(name = "telefono_referencia", unique = false, nullable = false, length = 255)
    private String telefonoReferencia;
    @Column(name = "direccion_referencia", unique = false, nullable = false, length = 255)
    private String direccionReferencia;
    @Column(name = "monto_solicitud", unique = false, nullable = false, length = 255)
    private Integer montoSolicitud;
    @Column(name = "estado", unique = false, nullable = false, length = 255)
    private String estado;
    @Column(name = "fecha_solicitud", unique = false, nullable = false, length = 255)
    private Date fechaSolicitud;

    public Solicitudes() {
    }

    public Solicitudes(int idSolicitud, String tipoSolicitud, String idCliente, String idReferencia, String nombreReferencia, String telefonoReferencia, String direccionReferencia, Integer montoSolicitud, String estado, Date fechaSolicitud) {
        this.idSolicitud = idSolicitud;
        this.tipoSolicitud = tipoSolicitud;
        this.idCliente = idCliente;
        this.idReferencia = idReferencia;
        this.nombreReferencia = nombreReferencia;
        this.telefonoReferencia = telefonoReferencia;
        this.direccionReferencia = direccionReferencia;
        this.montoSolicitud = montoSolicitud;
        this.estado = estado;
        this.fechaSolicitud = fechaSolicitud;
    }

    public int getIdSolicitud() {
        return this.idSolicitud;
    }

    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getTipoSolicitud() {
        return this.tipoSolicitud;
    }

    public void setTipoSolicitud(String tipoSolicitud) {
        this.tipoSolicitud = tipoSolicitud;
    }

    public String getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    public String getIdReferencia() {
        return this.idReferencia;
    }

    public void setIdReferencia(String idReferencia) {
        this.idReferencia = idReferencia;
    }

    public String getNombreReferencia() {
        return this.nombreReferencia;
    }

    public void setNombreReferencia(String nombreReferencia) {
        this.nombreReferencia = nombreReferencia;
    }

    public String getTelefonoReferencia() {
        return this.telefonoReferencia;
    }

    public void setTelefonoReferencia(String telefonoReferencia) {
        this.telefonoReferencia = telefonoReferencia;
    }

    public String getDireccionReferencia() {
        return this.direccionReferencia;
    }

    public void setDireccionReferencia(String direccionReferencia) {
        this.direccionReferencia = direccionReferencia;
    }

    public Integer getMontoSolicitud() {
        return this.montoSolicitud;
    }

    public void setMontoSolicitud(Integer montoSolicitud) {
        this.montoSolicitud = montoSolicitud;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }

    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

}
